import { advanced, esc, header, status } from '../components'; import type { ConsoleData, PluginView } from '../types';
function pluginRow(p: PluginView): string { return `<div class="resource-row"><div><h3>${esc(p.name)}</h3><div class="meta">${esc(p.description??'')}</div><div class="tags">${(p.capabilityLabels??[]).slice(0,6).map(c=>`<span class="tag">${esc(c)}</span>`).join('')}</div></div><div class="right">${status(p.statusLabel??p.status??'Unknown',p.status??p.tone)}<button class="btn" data-select-capability="${esc(p.id)}">Details</button></div></div>`; }
export function renderCapabilities(data: ConsoleData, selectedId?: string): string {
 const plugins=data.commandCenter.plugins??[], providers=data.automationSettings.providers??[], tools=data.automationSettings.localTools??[];
 const selected=plugins.find(p=>p.id===selectedId)??plugins[0];
 return header('Capabilities','从“Forge 能做什么”出发查看扩展、服务、执行工具与模型；底层 action/schema 只在 Advanced 中出现。','<button class="btn" data-refresh>Refresh</button>')+
 `<div class="tabs"><button class="tab active">All</button><span class="meta">${plugins.length} extensions/services · ${providers.length} models/providers · ${tools.length} local tools</span></div>`+
 `<div class="split"><div class="surface">${plugins.map(pluginRow).join('')}${providers.map(p=>`<div class="resource-row"><div><h3>${esc(p.displayName)}</h3><div class="meta">Model / provider · ${esc(p.explanation??p.summary??'')}</div></div>${status(p.statusLabel??p.status??'Unknown',p.status)}</div>`).join('')}${tools.map(t=>`<div class="resource-row"><div><h3>${esc(t.displayName)}</h3><div class="meta">Execution tool · ${esc(t.summary??'')}</div></div>${status(t.status??'Unknown',t.status)}</div>`).join('')}</div>`+
 `<aside class="surface detail">${selected?`<h2>${esc(selected.name)}</h2><div class="meta">${esc(selected.description??'')}</div><div class="detail-grid"><dt>Status</dt><dd>${status(selected.statusLabel??selected.status??'Unknown',selected.status??selected.tone)}</dd><dt>Provider</dt><dd>${esc(selected.provider??'—')}</dd><dt>Health</dt><dd>${esc(selected.healthLabel??'—')}</dd><dt>Lifecycle</dt><dd>${esc(selected.lifecycleLabel??'—')}</dd></div>${selected.nextStep?`<div class="notice"><strong>Next step</strong><span>${esc(selected.nextStep)}</span></div>`:''}<div class="tags">${(selected.capabilityLabels??[]).map(c=>`<span class="tag">${esc(c)}</span>`).join('')}</div>${advanced({actions:selected.actions,warnings:selected.warnings,advanced:selected.advanced},'Actions & protocol')}</aside>`:'<div class="empty">Select a capability</div>'}</div>`;
}
