import { describe, expect, test } from 'bun:test';
import type { ExecutionJob } from '../../src/runtime/execution/jobs/types';
import type { ProcessCheckReceiptEvidence } from '../../packages/kernel/work/api/index';
import { OPERATIONAL_SIGNAL_DEFINITIONS, OPERATIONAL_TARGET_DEFINITIONS, rankOperationalShadowPriors, reduceOperationalObservations, replayOperationalPriors, resolveOperationalShadowPrior, type OperationalObservation } from '../../packages/kernel/memory/api/index';
import { extractExecutionJobShadowObservation, extractProcessCheckShadowObservation } from '../../src/runtime/evidence/operational-shadow';

const scope={schemaVersion:1 as const,kind:'project' as const,id:'fixture-project'};
const retainedUntil='2026-10-01T00:00:00.000Z';
const asOf='2026-09-04T00:00:00.000Z';
const compatibility={operation:'repository.check',environment:'env-a'} as const;
function job(input:Partial<ExecutionJob>={}):ExecutionJob{return{schemaVersion:1,revision:1,jobId:'job-1',repoId:'repo-1',type:'check',status:'succeeded',priority:'P2',requestId:'req-1',semanticKey:'fixture',payload:{operation:'repository.check',arguments:{ignored:'private-reasoning-sentinel'}},origin:{surface:'system'},resourceClaims:[],dependencies:[],leaseRefs:[],createdAt:'2026-09-03T00:00:00.000Z',updatedAt:'2026-09-03T00:00:01.000Z',queuedAt:'2026-09-03T00:00:00.000Z',startedAt:'2026-09-03T00:00:00.100Z',finishedAt:'2026-09-03T00:00:01.000Z',attempt:1,maxAttempts:1,result:{ignored:'transcript-sentinel'},evidenceIds:[],...input}}
function receipt(input:Partial<ProcessCheckReceiptEvidence>={}):ProcessCheckReceiptEvidence{return{schemaVersion:1,receiptId:'receipt-1',resultDigest:'digest-1',repoId:'repo-1',checkId:'package:check:type',requestId:'check-req-1',processId:'process-1',checkEnvironmentFingerprint:'env-check',status:'passed',runtimeStatus:'succeeded',ok:true,timedOut:false,cancelled:false,artifactPath:'/tmp/ignored-sensitive-path',summary:'semantic-rationale-sentinel',startedAt:'2026-09-03T00:00:00.000Z',finishedAt:'2026-09-03T00:00:00.500Z',...input}}
function observation(input:{id:number;action?:'baseline'|'candidate';status?:ExecutionJob['status'];consumerRequestId?:string;environment?:string;metricId?:'latency_ms'|'success_rate'}):OperationalObservation{const requestId=`req-${input.id}`;return extractExecutionJobShadowObservation(job({jobId:`job-${input.id}`,revision:input.id,requestId,status:input.status??'succeeded',startedAt:`2026-09-03T00:00:${String(input.id).padStart(2,'0')}.000Z`,finishedAt:`2026-09-03T00:00:${String(input.id).padStart(2,'0')}.500Z`,updatedAt:`2026-09-03T00:00:${String(input.id).padStart(2,'0')}.500Z`}),{targetId:'mechanical_candidate_ordering',actionId:input.action??'candidate',metricId:input.metricId??'latency_ms',scope,consumerRequestId:input.consumerRequestId??requestId,retainedUntil,environmentFingerprint:input.environment??'env-a'})}

describe('Stage7E shadow operational priors',()=>{
 test('uses closed code-owned registries and emits shadow-only priors',()=>{expect(Object.keys(OPERATIONAL_SIGNAL_DEFINITIONS).sort()).toEqual(['execution_job.terminal_mechanical','process_check.terminal_mechanical']);expect(OPERATIONAL_TARGET_DEFINITIONS.mechanical_candidate_ordering.forbiddenDecisions).toContain('semantic_acceptance');const r=reduceOperationalObservations({observations:[observation({id:1}),observation({id:2}),observation({id:3})],asOf});expect(r.rejected).toEqual([]);expect(r.priors).toHaveLength(1);expect(r.priors[0].mode).toBe('shadow');expect(r.priors[0].readiness).toBe('shadow_candidate')});
 test('typed extractors ignore generic payload/result and semantic prose',()=>{const a=extractExecutionJobShadowObservation(job(),{targetId:'mechanical_candidate_ordering',actionId:'candidate',metricId:'latency_ms',scope,consumerRequestId:'req-1',retainedUntil,environmentFingerprint:'env-a'});const b=extractProcessCheckShadowObservation(receipt(),{targetId:'mechanical_candidate_ordering',actionId:'candidate',metricId:'latency_ms',scope,consumerRequestId:'check-req-1',retainedUntil,environmentFingerprint:'fallback-env'});const text=JSON.stringify([a,b]);for(const sentinel of ['private-reasoning-sentinel','transcript-sentinel','semantic-rationale-sentinel','ignored-sensitive-path'])expect(text).not.toContain(sentinel)});
 test('ambiguous attribution and normal contention waits never update a prior',()=>{const r=reduceOperationalObservations({observations:[observation({id:1,consumerRequestId:'different'}),observation({id:2,status:'waiting_for_workspace'})],asOf});expect(r.priors).toEqual([]);expect(r.rejected.map(x=>x.reason).sort()).toEqual(['ambiguous_attribution','inadmissible_outcome'])});
 test('small-N and duplicate observations remain insufficient',()=>{const a=observation({id:1}),b=observation({id:2});const r=reduceOperationalObservations({observations:[a,b,b],asOf});expect(r.priors[0].sampleCount).toBe(2);expect(r.priors[0].distinctEvidenceCount).toBe(2);expect(r.rejected.some(x=>x.reason==='duplicate_evidence')).toBe(true);expect(r.priors[0].readiness).toBe('insufficient_samples')});
 test('hard invalidation precedes ranking and time only decays effective sample weight',()=>{const prior=reduceOperationalObservations({observations:[observation({id:1}),observation({id:2}),observation({id:3})],asOf}).priors[0];const retained=new Set(prior.supportEvidenceRefs);const invalid=resolveOperationalShadowPrior({prior,compatibility:{operation:'repository.check',environment:'env-b'},retainedEvidenceRefs:retained,asOf});expect(invalid.status).toBe('invalidated');expect(invalid.ageWeight).toBe(0);const current=resolveOperationalShadowPrior({prior,compatibility,retainedEvidenceRefs:retained,asOf:'2026-09-10T00:00:00.000Z'});expect(current.status).toBe('shadow_candidate');expect(current.ageWeight).toBeGreaterThan(0);expect(current.ageWeight).toBeLessThan(1)});
 test('missing authoritative evidence creates replay gap',()=>{const prior=reduceOperationalObservations({observations:[observation({id:1}),observation({id:2}),observation({id:3})],asOf}).priors[0];expect(resolveOperationalShadowPrior({prior,compatibility,retainedEvidenceRefs:new Set(prior.supportEvidenceRefs.slice(1)),asOf}).status).toBe('replay_gap')});
 test('replay is deterministic and ranking remains out-of-band',()=>{const observations=[1,2,3].flatMap(id=>[observation({id,action:'baseline'}),observation({id:id+3,action:'candidate'})]);const forward=replayOperationalPriors({observations,asOf}),reverse=replayOperationalPriors({observations:[...observations].reverse(),asOf});expect(reverse).toEqual(forward);const retained=new Set(forward.priors.flatMap(p=>p.supportEvidenceRefs));const ranked=rankOperationalShadowPriors({priors:forward.priors,compatibility,retainedEvidenceRefs:retained,asOf});expect(ranked).toHaveLength(2);expect(ranked.every(x=>x.prior.mode==='shadow')).toBe(true)});
 test('enforces registered retention horizon and bounded signal scope cardinality',()=>{const tooLong=observation({id:1});tooLong.source.retainedUntil='2027-12-01T00:00:00.000Z';const many=Array.from({length:129},(_,i)=>{const o=observation({id:(i%59)+1});o.observationId=`scope-${i}`;o.source.sourceId=`source-${i}`;o.source.evidenceRef=`evidence-${i}`;o.attribution.sourceId=o.source.sourceId;o.scope={schemaVersion:1,kind:'project',id:`scope-${i}`};return o});const r=reduceOperationalObservations({observations:[tooLong,...many],asOf});expect(r.rejected.some(x=>x.reason==='retention_horizon_exceeded')).toBe(true);expect(r.rejected.some(x=>x.reason==='scope_cardinality_exceeded')).toBe(true)});
 test('caps compatibility buckets and samples so shadow state cannot grow without bound',()=>{const sameBucket=Array.from({length:65},(_,i)=>{const o=observation({id:(i%59)+1});o.observationId=`sample-${i}`;o.source.sourceId=`sample-source-${i}`;o.source.evidenceRef=`sample-evidence-${i}`;o.source.requestId=`sample-request-${i}`;o.attribution.sourceId=o.source.sourceId;o.attribution.requestId=o.source.requestId;return o});const capped=reduceOperationalObservations({observations:sameBucket,asOf});expect(capped.priors[0].sampleCount).toBe(64);expect(capped.rejected.some(x=>x.reason==='sample_cap_exceeded')).toBe(true);const compatibilityMany=Array.from({length:257},(_,i)=>{const o=observation({id:(i%59)+1});o.observationId=`compat-${i}`;o.source.sourceId=`compat-source-${i}`;o.source.evidenceRef=`compat-evidence-${i}`;o.source.requestId=`compat-request-${i}`;o.attribution.sourceId=o.source.sourceId;o.attribution.requestId=o.source.requestId;o.compatibility={operation:`op-${i}`,environment:'env-a'};return o});const bounded=reduceOperationalObservations({observations:compatibilityMany,asOf});expect(bounded.rejected.some(x=>x.reason==='compatibility_cardinality_exceeded')).toBe(true)});
 test('process-check extractor derives only mechanical identity/status/timing compatibility',()=>{const o=extractProcessCheckShadowObservation(receipt(),{targetId:'mechanical_candidate_ordering',actionId:'candidate',metricId:'success_rate',scope,consumerRequestId:'check-req-1',retainedUntil,environmentFingerprint:'fallback-env'});expect(o.outcomeClass).toBe('executed_success');expect(o.value).toBe(1);expect(o.compatibility).toEqual({operation:'check:package:check:type',environment:'env-check'})});
});
