export {
  WorkspaceTargetGrantError,
  authorizeWorkspaceTargetGrant,
  getActiveWorkspaceTargetGrant,
  listActiveWorkspaceTargetGrants,
  resolveWorkspaceTargetCwd,
  resolveWorkspaceTargetPath,
  workspaceTargetGrantStorePath,
  type ActiveWorkspaceTargetGrant,
  type AuthorizeWorkspaceTargetGrantInput,
  type ResolvedWorkspaceTargetPath,
  type ResolveWorkspaceTargetPathOptions,
  type WorkspaceTargetAccess,
  type WorkspaceTargetGitIdentity,
  type WorkspaceTargetGitKind,
  type WorkspaceTargetGrant,
  type WorkspaceTargetGrantErrorCode,
  type WorkspaceTargetOperation,
} from './target-grant';
