/** Stable Scheduler lifecycle façade. Persistence remains internal to the Scheduler module. */
export {
  applyScheduleDedupe,
  buildScheduleDedupeReport,
  cleanupScheduleOccurrenceHistory,
  createSchedule,
  deleteSchedule,
  getOccurrence,
  getSchedule,
  getScheduleDecision,
  listActiveOccurrences,
  listOccurrences,
  reclaimStaleCreatedOccurrences,
  listSchedules,
  recordScheduleOccurrenceHandoff,
  saveOccurrence,
  saveSchedule,
  saveScheduleDecision,
  updateSchedule,
  getScheduleDefinition,
  getScheduleRuntimeState,
  type ScheduleHistoryCleanupResult,
  type ScheduleDedupeApplyResult,
  type ScheduleDedupeReport,
  type ScheduleDuplicateGroup,
  type ScheduleDuplicateMember,
} from '../infrastructure/schedule-store';
